#!/usr/bin/env -S node --no-warnings --stack-trace-limit=1000

require("events").EventEmitter.defaultMaxListeners = 0

const { cli, dbug } = require("@foundernetes/blueprint")

dbug.registerGlobal()

const playbooks = require("~/playbooks")

const loadLocalConfig = require("./.foundernetesrc")
const pk = require("./package.json")

const main = async () => {
  const config = await loadLocalConfig()

  await cli(process.argv, {
    customProgram: {
      name: "machines",
      version: pk.version,
      description: pk.description,
      enabledCommands: ["playbook"],
    },
    defaultCommand: "playbook",
    inlineConfigs: [config],
    playbookSet: {
      playbooks,
    },
  })
}

main()
