#!/usr/bin/env -S node --no-warnings --stack-trace-limit=1000

require("events").EventEmitter.defaultMaxListeners = 0

const shellQuote = require("shell-quote")
const { cli, dbug, ctx } = require("@foundernetes/blueprint")
const cliMachines = require("@foundernetes/machines/cli-plugin")
const dayjs = require("dayjs")

dbug.registerGlobal()

const playbooks = require("~/playbooks")

const loadLocalConfig = require("./.foundernetesrc")

const main = async () => {
  const localConfig = await loadLocalConfig()

  const now = dayjs().format("YYYY-MM-DD-HH-mm-ss")

  await cli(process.argv, {
    inlineConfigs: [localConfig],
    playbookSet: {
      playbooks,
    },
    cliPlugins: [
      cliMachines({
        cwd: localConfig.remoteCwd,
        selfUploadTarget: "metal-debian",
        selfUploadDist: true,
        selfUploadDevPath: `${__dirname}/dist-bin/metal-debian`,
        extraUpload: [
          {
            source: `${process.cwd()}/metal-debian.yaml`,
            target: "metal-debian.yaml",
          },
        ],
        extraCommands: [
          () => {
            const config = ctx.getConfig()
            const tagsArgs = shellQuote.quote(
              (config.tags || []).map((t) => ["-t", t]).flatMap((a) => a)
            )
            return {
              command: `sudo ./metal-debian ${tagsArgs}`,
              logWrap: false,
              env: {
                F10S_LOG_LEVEL: "trace",
                F10S_LOG_FILE: `/var/log/metal-debian/machines-${now}.log`,
                F10S_LOG_FILE_PLAIN: `/var/log/metal-debian/plain.machines-${now}.log`,
                FORCE_COLOR: 2,
              },
            }
          },
        ],
      }),
    ],
  })
}

main()
