#!/usr/bin/env -S node --no-warnings --stack-trace-limit=1000

require("events").EventEmitter.defaultMaxListeners = 0

const { cli, dbug } = require("@foundernetes/blueprint")

const pk = require("./package.json")

dbug.registerGlobal()

const main = async () => {
  await cli(process.argv, {
    customProgram: {
      name: "projekto",
      version: pk.version,
      description: pk.description,
      enabledCommands: ["playbook"],
    },
    defaultCommand: "playbook",
  })
}

main()
