#!/usr/bin/env -S node --no-warnings --stack-trace-limit=1000

require("events").EventEmitter.defaultMaxListeners = 0

const fs = require("fs-extra")
const { cli, dbug } = require("@foundernetes/blueprint")
const yarn = require("~/utils/yarn")

dbug.registerGlobal()

const main = async () => {
  if (await fs.pathExists(`${process.cwd()}/package.json`)) {
    await yarn()
  }

  await cli(process.argv, {
    defaultCommand: "snippet",
  })
}

main()
