name: Publish

on:
  push:
    tags:
      - v*.*

concurrency:
  cancel-in-progress: true
  group: release-${{ github.ref_name }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Publish
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        #   NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          yarn --immutable
          yarn publish